services:
  frontend:
    build: ./form
    restart: unless-stopped
    ports:
      - 3000:3000
  backend:
    build: ./api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3001:3001
    volumes:
      - ./api/forms:/app/forms
    environment:
      - JWT_SECRET
  postgres:
    build: ./db
    restart: unless-stopped
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U formuser -d forms"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
